# Generated by Django 3.0.6 on 2020-07-14 09:05

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200703_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('img_file', models.ImageField(upload_to=core.models.path_file_name)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='core.Post')),
            ],
        ),
    ]
